forms.py
from flask_wtf import FlaskForm
from wtforms import Form, StringField, RadioField, SelectField, TextAreaField, EmailField, SubmitField, validators


class createEnquiryForm(Form):
    name = StringField('Name', [validators.length(3, 128, message='Name must be between 3 to 128 characters'),
                                validators.DataRequired(message='Name is required')])
    email = EmailField('Email', [validators.Email(granular_message=True),
                                 validators.DataRequired(message='Email is required')])
    purpose = SelectField('Purpose', [validators.DataRequired('Purpose is required')],
                          choices=[("", 'Select a Purpose'), ('General Questions', 'General Questions'),
                                   ('Feedback / Feature Request', 'Feedback / Feature Request')], default=""
                          )
    query = TextAreaField('Enquiry',
                          [validators.length(3, 1000, message='Enquiry must be between 3 to 1000 characters'),
                           validators.DataRequired('Enquiry is required')])
    submit = SubmitField('Submit')

app.py
from flask import Flask, render_template
from routes.enquiry import enquiry
from routes.south import south

app = Flask(__name__)
app.secret_key = 'RTYUjnbgf59ij34rhgieudfk'

app.register_blueprint(enquiry)
app.register_blueprint(south)


@app.route('/')
def home():
    return render_template('home.html')




if __name__ == '__main__':
    app.run(debug=True)

routes/enquiry.py
import shelve

from flask import Blueprint, render_template
from flask import flash, render_template, redirect, url_for, request

from classes.Enquiry import Enquiry
from forms import createEnquiryForm

enquiry = Blueprint('enquiry', __name__)


@enquiry.route('/ContactUs', methods=['GET', 'POST'])
def viewEnquiry():
    form = createEnquiryForm(request.form)

    if request.method == 'POST' and form.validate():
        name = form.name.data
        email = form.email.data
        purpose = form.purpose.data
        query = form.query.data
        this_enquiry = Enquiry(name, email, purpose, query)

        with shelve.open('enquiry', writeback='True') as enquiries:
            enquiries[str(this_enquiry.getId())] = this_enquiry

        flash('Thank you for contacting Explore Singapore. We will get back to you shortly.', category='success')
        return redirect(url_for("enquiry.viewEnquiry"))
    else:
        flash('Unable to create form, please retry again!')
    return render_template("enquiry/viewEnquiry.html", form=form)

routes/south.py
import shelve

from flask import Blueprint, render_template
from flask import flash, render_template, redirect, url_for, request

from classes.Enquiry import Enquiry
from forms import createEnquiryForm

south = Blueprint('south', __name__)


@south.route('/south/LazarusIsland')
def viewLazarusIsland():
    return render_template("south/Lazarus_Island.html")

templates/base.html
{% import "includes/formHelper.html" as formHelper %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
          rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
</head>
<body>

    {% block navbar %}
        {% include "includes/navbar.html" %}
    {% endblock%}

    {% block breadcrumb %}
        <ul class="breadcrumb">
            <li><a href="{{ url_for('home')  }}">Home</a></li>
        </ul>
    {% endblock breadcrumb %}


    {% block content %}
    {% endblock %}


</body>
{% block footer %}
    {% include "includes/footer.html" %}
{% endblock %}
{% block scripts %}{% endblock %}
</html>

templates/enquiry/viewEnquiry.html
{% extends "base.html" %}
{% block title %}Explore Singapore - Contact Us{% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg-6">
        <form method = 'post' enctype="multipart/form-data">
            <div class="mb-3">
                {{ formHelper.renderField(form.name) }}
            </div>
            <div class="mb-3">
                {{ formHelper.renderField(form.email) }}
            </div>
            <div class="mb-3">
                {{ formHelper.renderField(form.purpose) }}
            </div>
            <div class="mb-3">
                {{ formHelper.renderField(form.query) }}
            </div>
            <div class="mb-3">
                {{ formHelper.renderField(form.submit) }}
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/home.html
{% extends "base.html" %}
{% block title %}Explore Singapore - Home {% endblock %}

{% block content %}
<section class="showcase">
    <div class="video-container">
      <video src="../static/vid/vid.mp4" autoplay muted loop></video>
    </div>
    <div class="content">
      <h1>Explore Singapore</h1>
      <h3>With a new outlook!</h3>
      <a href="#about" class="btn" style="color:white; border: solid white 1px;">Read More</a>
    </div>
</section>
<div class="container" id="container2">
    <section id="about">
        <h1 id="header">About</h1>
        <p>
            Explore and visit new places around Singapore that are not so well known! Bring your family and friends along for a fun and enjoyable trip!
        </p>
    </section>
</div>
{% endblock %}

templates/includes/footer.html
<!-- Footer -->
<footer class="text-center text-lg-start text-white">
    <!-- Section: Social media -->
    <section class="d-flex justify-content-between p-4" style="background-color: #c60021; ">
        <!-- Left -->
        <div class="me-5">
            <span>Get connected with us on social networks:</span>
        </div>
        <!-- Left -->
        <!-- Right -->
        <div>
            <a href="" class="text-white me-4">
                <i class="fa fa-facebook-f"></i>
            </a>
            <a href="" class="text-white me-4">
                <i class="fa fa-twitter"></i>
            </a>
            <a href="https://www.instagram.com/" class="text-white me-4">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
                    <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
                </svg>
            </a>
        </div>
        <!-- Right -->
    </section>
    <!-- Section: Links  -->
    <section class="">
        <div class="container text-center text-md-start mt-5 text-black" >
            <!-- Grid row -->
            <div class="row">
                <!-- Grid column -->
                <div class="col-sm-4"  ">
                    <!-- Content -->
                    <h6 class="text-uppercase fw-bold">Explore Singapore</h6>
                    <hr class="mb-4 mt-0 d-inline-block mx-auto" style="width: 60px; background-color: #c60021; height: 2px;" />
                    <p>
                        Explore Singapore with a new outlook, and you never know what you might find!
                    </p>
                </div>
                <!-- Grid column -->
                <div class="col-sm-4" >
                    <!-- Links -->
                    <h6 class="text-uppercase fw-bold">Places to Explore</h6>
                    <hr class="mb-4 mt-0 d-inline-block mx-auto" style="width: 60px; background-color: #c60021; height: 2px;" />
                    <p>
                        <a href="#!">North</a>
                    </p>
                    <p>
                        <a href="#!">South</a>
                    </p>
                    <p>
                        <a href="#!">East</a>
                    </p>
                    <p>
                        <a href="#!">West</a>
                    </p>
                    <p>
                        <a href="#!">Central</a>
                    </p>
                </div>
                <div class="col-sm-4">
                    <!-- Links -->
                    <h6 class="text-uppercase fw-bold">Contact</h6>
                    <hr class="mb-4 mt-0 d-inline-block mx-auto" style="width: 60px; background-color: #c60021; height: 2px;" />
                    <p>Singapore, Singapore</p>
                    <p>info@exploresingapore.com</p>
                    <p>+65 9297 7389</p>
                </div>
                <div class="col-sm">
                    <p class="d-flex justify-content-center align-items-center">
                        <span class="me-3" style="padding-right: 20px">Register for our newsletter!</span>
                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                            Sign Up Now!
                        </button>
                    </p>
                </div>
            </div>
        </div>
    </section>

</footer>
<!-- Footer -->

templates/includes/formHelper.html
{% macro renderField(field, w=False) %}
    {% if not field.type == "SubmitField" and not field.type == "BooleanField" %}
        <div class="d-flex align-items-center">
            {{ field.label(class="form-label me-2") }}
            {% if field.flags.required %}
                <span style="color: red" data-bs-toggle="tooltip" data-bs-title="Required Field" data-bs-placement="right">*</span>
            {% endif %}
        </div>
    {% endif %}
    {% if field.type == "RadioField" %}
        {% for item in field %}
            <div class="form-check">
                {{ item(class="form-check-input")|safe }} {{item.label(class="form-check-label")|safe}}
            </div>
        {% endfor %}
    {% elif field.type == "BooleanField" %}
        <div class="form-check">
            {{ field(class="form-check-input")|safe }} {{field.label(class="form-check-label")|safe}}
        </div>
    {% elif field.type == "SubmitField" %}
        {% if w %}
            {{ field(class="btn custom-btn w-100", **kwargs)|safe }}
        {% else %}
            {{ field(class="btn custom-btn", **kwargs)|safe }}
        {% endif %}
    {% else %}
        {{ field(class="form-control", placeholder=field.label.text, **kwargs)|safe }}
        {% if field.errors %}
            <div class="mt-1">
                {% for error in field.errors %}
                    <div class="text-danger">{{ error }}</div>
                {% endfor %}
            </div>
        {% endif %}
    {% endif %}
{% endmacro %}

templates/includes/navbar.html
<!--Navbar for website-->
<nav class="navbar navbar-expand-lg navbar-light " style="z-index: 1000000;">
    <a class="navbar-brand" href="../homepage/index.html" style="font-weight: bold;">Explore Singapore</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent" >
        <ul class="navbar-nav mr-auto" id="navbar" >
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('home')  }}"><h5 >Home</h5><span class="sr-only"></span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="../aboutus/aboutus.html"><h5 >About Us</h5></a>
            </li>
            <li class="nav-item dropdown" style="display: inline-block;" >
                <a class="nav-link dropdown-toggle d-flex align-items-center" href="#" data-bs-toggle="dropdown"><h5>Places to visit</h5></a>
                <div class="dropdown-menu dropdown-large">
                    <div class="row g-3">
                        <div class="col-4">
                            <h4 class="title"><a href="../places to visit/places to visit.html">Places to Visit</a></h4>
                        </div>
                    </div>
                    <div class="row g-3">
                        <div class="col-4">
                            <h5 class="title"><a href="../north/north.html">North</a></h5>
                            <ul class="list-unstyled">
                                <li><a href="../north/Hampstead Wetlands Park.html">Hampstead Wetlands Park</a></li>
                                <li><a href="../north/Kranji Marshes.html">Kranji Marshes</a></li>
                            </ul>
                        </div>
                        <!-- end col-3 -->
                        <div class="col-4">
                            <h5 class="title"><a href="../south/south.html">South</a></h5>
                            <ul class="list-unstyled">
                                <li><a href="../south/St%20James%20Power%20Station.html">St James Power Station</a></li>
                                <li><a href="../south/Rotunda_Library_Archive.html">Rotunda Library & Archive</a></li>
                                <li><a href="../south/Wood_in_the_Books.html">Wood in the Books</a></li>
                                <li><a href="../south/Vintage_Camera_Museum.html">Vintage Camera Museum</a></li>
                                <li><a href="{{ url_for('south.viewLazarusIsland')  }}">Lazarus Island</a></li>
                                <li><a href="../south/Berlayer_Creek_Boardwalk.html">Berlayer Creek Boardwalk</a></li>
                            </ul>
                        </div>
                        <!-- end col-3 -->
                        <div class="col-4">
                            <h5 class="title"><a href="../east/east.html">East</a></h5>
                            <ul class="list-unstyled">
                                <li><a href="../east/Changi Bay Point.html">Changi Bay Point</a></li>
                                <li><a href="../east/Japanese Cemetery Park.html">Japanese Cemetry Park</a></li>
                            </ul>
                        </div>
                        <!-- end col-3 -->
                    </div>
                    <!-- end row -->
                    <hr style="background-color: white;" />
                    <div class="row g-3">
                        <div class="col-4">
                            <h5 class="title"><a href="../west/west.html">West</a></h5>
                            <ul class="list-unstyled">
                                <li><a href="../west/Junkies Corner.html">Junkies Corner</a></li>
                                <li><a href="../west/Maju Forest.html">Maju Forest</a></li>
                            </ul>
                        </div>
                        <!-- end col-3 -->
                        <div class="col-4">
                            <h5 class="title"><a href="../central/central.html">Central</a></h5>
                            <ul class="list-unstyled">
                                <li><a href="../central/Dragon Playground.html">Dragon Playground </a></li>
                                <li><a href="../central/National Orchid Garden.html">National Orchid Garden </a></li>
                            </ul>
                        </div>
                        <!-- end col-3 -->
                    </div>
                    <!-- end row -->
                    <!-- end row -->
                </div>
                <!-- dropdown-large.// -->
            </li>
            <li class="nav-item" >
                <a class="nav-link d-flex align-items-center" href="../blog/blog home.html"><h5>Blog</h5></a>
            </li>
        </ul>
    </div>
</nav>
<script type="text/javascript">
    document.addEventListener("DOMContentLoaded", function () {
        /////// Prevent closing from click inside dropdown
        document.querySelectorAll(".dropdown-menu").forEach(function (element) {
            element.addEventListener("click", function (e) {
                e.stopPropagation();
            });
        });
    });
</script>

templates/south/Lazarus_Island.html
{% extends "base.html" %}
{% block title %}Explore Singapore - Lazarus Island {% endblock %}

{% block content %}
<style>
    #containerabout {
        width: 100%;
        height: 90vh;
        background: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url(https://media.cntraveler.com/photos/5a9174c820dfb6552425e85d/16:9/w_1920,c_limit/Lazarus-Island_GettyImages-481012244.jpg);
        background-size: cover;
        background-position: center center;
        background-repeat: no-repeat;
        display: flex;
        align-items: center;
        justify-content: center;
        color: #fff;
        font-size: 2vw;
        max-height: 600px;
    }
</style>
<body>

        <!-- breadcrumbs -->
        <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="../homepage/index.html">Home</a></li>
                <li class="breadcrumb-item"><a href="../places to visit/places to visit.html">Places to Explore</a></li>
                <li class="breadcrumb-item"><a href="/south.html">South</a></li>
                <li class="breadcrumb-item active" aria-current="page">Lazarus Island</li>
            </ol>
        </nav>

    <!-- Header Image -->

        <div id="containerabout">
            <div class="centered">
                <h2 class="headerabout" id="header">Lazarus Island</h2>
            </div>
        </div>

    <div class="container" id="containerbackground">
        <div class="container" id="container2">
            <div class="row">
                <div class="col-12">
                    <h2 class="header">About Us</h2>
                </div>
                <div class="col-12">
                    <p>
                    On Lazarus Island in the late 19th century, there were a number of prison confinement sheds, but they were abandoned when an inmate serving a life sentence there managed to escape. The confinement barns were completely burned by a wildfire in 1902, and the entire area's vegetation was completely devastated by a huge fire in 1914. Lazarus Island was intended to be turned into a beach resort by the government, but those plans were never carried out. Lazarus Island attracts throngs of tourists who come to enjoy the spotless white sand beach on the C-shaped lagoon. It has also been referred to as one of Singapore's best-kept secrets and one of the forgotten islands. Lazarus Island attracts beachgoers and families seeking some peaceful time to be with loved ones.
                    </p>
                </div>
                <div class="col-12">
                    <h2 class="header">Places to Explore</h2>
                </div>
                <div class="col-12">
                    <iframe width="1223" height="688" src="https://www.youtube.com/embed/KW5dP3qQV_E" title="Hidden Gems in Singapore (St. John's Island and Lazarus Island)" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                </div>


                <p>Credits: <a href="https://www.cntraveler.com/activities/singapore/lazarus-island" target="_blank" rel="noopener noreferrer">CNTraveler</a>, <a href="https://islandcruise.com.sg/places-of-interest/lazarus-island/" target="_blank" rel="noopener noreferrer">Island Cruise</a></p>
            </div>
        </div>
        <div class='container' id="container2">
            <div class="row">
                <div class="col-6">
                    <h2 class="header">Map</h2>
                    <div class="iframe-rwd">
                        <iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d11282.343534406686!2d103.84776495644498!3d1.222066929775941!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31da1ee8b3f07ab9%3A0x734f010b626b98ce!2sLazarus%20Island!5e0!3m2!1sen!2ssg!4v1659269187657!5m2!1sen!2ssg" ></iframe>
                        <br>
                        <small>
                          <a href="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d11282.343534406686!2d103.84776495644498!3d1.222066929775941!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31da1ee8b3f07ab9%3A0x734f010b626b98ce!2sLazarus%20Island!5e0!3m2!1sen!2ssg!4v1659269187657!5m2!1sen!2ssg"   style="color:#0000FF;text-align:left">View Larger Map</a>
                        </small>
                    </div>
                </div>
                <div class = 'col-6'>
                    <h2 class="header">Operating Hours</h2>
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>Days</th><th>Timing</th>
                            </tr>
                        </thead>
                        <tbody >
                            <tr>
                                <td>Monday-Sunday</td><td>Open 24 hours</td>
                            </tr>
                        </tbody>
                    </table>
                    <p>*Please note that some venues may be subject to opening hours, please visit their official website to confirm opening hours</p>

                </div>
            </div>
        </div>
    </div>

    <!-- End of .container -->
    <script type="text/javascript">
        var myModal = document.getElementById("myModal");
        var myInput = document.getElementById("myInput");
        myModal.addEventListener("shown.bs.modal", function () {
            myInput.focus();
        });
    </script>
</body>
{%  endblock %}